# Generated by Django 5.1.6 on 2025-03-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_taskmodel_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.tagmodel'),
        ),
    ]
