# Generated by Django 5.1.6 on 2025-03-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('task', '0003_taskmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='project.projectmodel'),
        ),
    ]
