# Generated by Django 5.1.7 on 2025-03-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('tag', models.ManyToManyField(blank=True, related_name='tasks', to='tag.tagmodel')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
