# Generated by Django 5.1.7 on 2025-03-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='task.taskmodel')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
