# Generated by Django 5.1.6 on 2025-02-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
            ],
            options={
                'db_table': 'auto_park',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.autoparkmodel')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
